# Cleaning and exploring Data

In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
from mpl_toolkits import mplot3d

In [2]:
df = pd.read_csv('augmented.csv', header=None)

In [3]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,591,592,593,594,595,596,597,598,599,600
0,1.0,0.013694,0.024678,0.130142,0.000040,-0.092436,-0.084620,0.001543,0.019859,0.120984,...,0.127987,-0.000244,0.005662,-0.000609,0.004237,0.010671,0.128107,-0.000149,0.004620,-0.000293
1,1.0,0.017053,0.020579,0.135425,0.000116,-0.084549,-0.091722,0.002638,0.021355,0.121782,...,0.130576,-0.000180,0.004984,-0.000616,0.006392,0.009465,0.124005,-0.000170,0.004364,-0.000438
2,1.0,0.014255,0.027313,0.129618,0.000151,-0.086681,-0.076629,-0.000785,0.017615,0.124429,...,0.134017,-0.000299,0.005270,-0.000436,0.004296,0.011953,0.127566,-0.000212,0.004342,-0.000235
3,1.0,0.000885,0.009893,0.126730,-0.000118,-0.010667,-0.021169,-0.003575,0.011060,0.124755,...,0.129274,0.000009,0.005978,0.003971,0.001723,0.009085,0.127807,0.000072,0.006862,0.000465
4,1.0,0.004139,0.010287,0.135432,-0.000064,-0.009910,-0.020790,-0.002217,0.013348,0.125830,...,0.134090,0.000199,0.005598,0.003782,0.007559,0.006795,0.132539,0.000112,0.006204,0.000511

In [4]:
num_features = 15
num_labels = 3
df_list = []

In [5]:
start_index = 0
end_index = num_features
for i in range(num_labels):
    df_list.append(df.iloc[start_index:end_index:])
    start_index+=num_features
    end_index+=num_features

In [6]:
df_list[2].head()

,0,1,2,3,4,5,6,7,8,9,...,591,592,593,594,595,596,597,598,599,600
30,2.0,0.019560,0.037158,0.123019,-0.000118,-0.026174,-0.038003,0.014802,0.036979,0.110568,...,0.173659,0.000009,0.044636,0.028859,0.009534,0.004386,0.176861,0.000040,0.039803,0.088899
31,2.0,0.020441,0.038430,0.116510,-0.000084,-0.027998,-0.035687,0.013228,0.035842,0.105712,...,0.160221,0.000129,0.048031,0.027032,0.012413,0.001999,0.169171,0.000094,0.042996,0.083403
32,2.0,0.019851,0.034404,0.124661,-0.000001,-0.024096,-0.034347,0.015680,0.034770,0.106327,...,0.175170,0.000037,0.041315,0.026108,0.007803,0.001742,0.180298,0.000234,0.036752,0.080209
33,2.0,-0.010818,-0.007107,0.127688,0.000009,0.000956,0.011993,-0.011356,-0.008723,0.130411,...,0.125623,0.000040,0.048394,-0.026539,-0.040477,-0.010998,0.127837,-0.000055,0.035824,-0.023728
34,2.0,-0.012643,-0.007654,0.131610,-0.000023,0.000848,0.011624,-0.011841,-0.010413,0.135737,...,0.128592,0.000339,0.047096,-0.025662,-0.037223,-0.004630,0.133013,0.000062,0.034935,-0.022737

In [7]:
for i in range(len(df_list)):
    df_list[i] = df_list[i].reset_index(drop=True)
    df_list[i] = df_list[i].transpose()
    df_list[i]['Label'] = df_list[i][0][0]
    df_list[i] = df_list[i].iloc[1:]

## Making a new dataframe (assuming that this is the right format)

In [8]:
df_main = pd.concat(df_list)

## Final data to be processed

In [9]:
df_main

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,Label
1,0.013694,0.017053,0.014255,0.000885,0.004139,0.001234,0.002860,0.004169,0.005537,-0.027728,-0.028059,-0.027055,-0.000253,-0.005057,0.002394,1.0
2,0.024678,0.020579,0.027313,0.009893,0.010287,0.007451,0.013634,0.010768,0.012484,0.012108,0.007040,0.011899,0.012766,0.013145,0.012304,1.0
3,0.130142,0.135425,0.129618,0.126730,0.135432,0.123417,0.127299,0.128082,0.122242,0.129483,0.130641,0.127442,0.125084,0.121038,0.129874,1.0
4,0.000040,0.000116,0.000151,-0.000118,-0.000064,-0.000026,0.000135,0.000117,0.000284,0.000009,-0.000042,0.000113,0.000040,0.000130,0.000038,1.0
5,-0.092436,-0.084549,-0.086681,-0.010667,-0.009910,-0.010683,0.008220,0.008988,0.008878,0.004620,0.004234,0.004512,0.007967,0.007772,0.008324,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,0.004386,0.001999,0.001742,-0.010998,-0.004630,-0.009682,-0.036138,-0.037395,-0.039540,-0.026082,-0.026924,-0.029524,-0.034851,-0.038620,-0.031104,2.0
597,0.176861,0.169171,0.180298,0.127837,0.133013,0.129462,0.159203,0.149089,0.149580,0.113950,0.114913,0.113960,0.122719,0.121997,0.118149,2.0
598,0.000040,0.000094,0.000234,-0.000055,0.000062,0.000053,0.000166,0.000129,0.000065,0.000135,0.000200,0.000196,0.000103,0.000283,0.000018,2.0
599,0.039803,0.042996,0.036752,0.035824,0.034935,0.037161,-0.087225,-0.090856,-0.095751,-0.011709,-0.012491,-0.011846,-0.011741,-0.011073,-0.012190,2.0
600,0.088899,0.083403,0.080209,-0.023728,-0.022737,-0.023908,0.026237,0.028139,0.024200,0.079645,0.075663,0.071926,-0.005946,-0.005483,-0.006263,2.0

## Using XGBoost to classify

In [10]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [12]:
X = df_main.iloc[:,0:num_features]
Y = df_main.iloc[:,num_features:]
X.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
1,0.013694,0.017053,0.014255,0.000885,0.004139,0.001234,0.002860,0.004169,0.005537,-0.027728,-0.028059,-0.027055,-0.000253,-0.005057,0.002394
2,0.024678,0.020579,0.027313,0.009893,0.010287,0.007451,0.013634,0.010768,0.012484,0.012108,0.007040,0.011899,0.012766,0.013145,0.012304
3,0.130142,0.135425,0.129618,0.126730,0.135432,0.123417,0.127299,0.128082,0.122242,0.129483,0.130641,0.127442,0.125084,0.121038,0.129874
4,0.000040,0.000116,0.000151,-0.000118,-0.000064,-0.000026,0.000135,0.000117,0.000284,0.000009,-0.000042,0.000113,0.000040,0.000130,0.000038
5,-0.092436,-0.084549,-0.086681,-0.010667,-0.009910,-0.010683,0.008220,0.008988,0.008878,0.004620,0.004234,0.004512,0.007967,0.007772,0.008324

In [13]:
seed = 7
test_size = 0.33
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [14]:
model = XGBClassifier()
model.fit(X_train, y_train.values.ravel())

XGBClassifier(objective='multi:softprob')

In [15]:
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

In [16]:
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 85.19%